name: Build and Upload as Encrypted Artifact (Manual Dispatch)

on:
  workflow_dispatch:

jobs:
  build:
    name: Building for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          path: Trier_25
          repository: gdw-tum/trier-25 # Change title for other workflows
          token: ${{ secrets.ACCESS_TOKEN_REPO }}

      - name: Cache files for faster build
        uses: actions/cache@v4
        with:
          path: Trier_25/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - name: Build project with Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: auto
          projectPath: ./Trier_25/
          versioning: Semantic
          buildName: Trier_25 # Change title for other workflows

      - name: Zip folder
        run: |
          if [ -d "$FOLDER" ]; then
            zip -r "$FOLDER.zip" "$FOLDER"
          else
            echo "Error: Folder $FOLDER does not exist."
            exit 1
          fi
        env:
          FOLDER: build

      - name: Encrypt build
        run: |
          gpg --quiet --batch --yes --symmetric --cipher-algo AES256 --passphrase="$PASSPHRASE" --output "$FILE.enc" "$FILE"
          rm "$FILE"
          echo "File encrypted successfully."
        env:
          PASSPHRASE: ${{ secrets.ARTIFACTS_PASSPHRASE }}
          FILE: ./build.zip

      - name: Upload build results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Trier_25-${{ matrix.targetPlatform }} # Change title for other workflows
          path: ./build.zip.enc
